### PR TITLE
update to v0.19.0

### PR DESCRIPTION
**Pull request by 0xbe7a**
- **update to v0.19.0**
- **rerender**
- ~**add myself as maintainer**~

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by 0xbe7a** [comment]
@jayqi, ready for review!

**Review by jayqi — CHANGES_REQUESTED** [review]
Hi @0xbe7a, thanks so much for looking into the build errors and submitting a PR with fixes to the build recipe. It's much appreciated!

However, I don't feel comfortable adding you as a maintainer to the feedstock. This isn't something we've previously discussed. I hope you understand.

**Comment by 0xbe7a** [comment]
Sure, just drop it, the PR is editable by maintainers

**Comment by jayqi** [comment]
@conda-forge-admin, please rerender

**Review by jayqi — APPROVED** [review]
Thanks for contributing the fixes!

**Pull request merged**
