### PR TITLE
Remove extra script entries

### PR DESCRIPTION
**Pull request by jayqi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jayqi** [comment]
@conda-forge-admin, please rerender

**Comment by jayqi** [comment]
@bollwyvl I've been having trouble getting the YAML anchors/aliases to work, or even find documentation about it in the context of conda recipes/conda-forge recipes. Do you have any insight on this? It would definitely be nice because I've already screwed up keeping the build number consistent between all of these subpackages...

**Comment by bollwyvl** [comment]
If the anchors aren't working, you can use additional Jinja variables, e.g

{% set build_number = "1" %}

And then : to

number: {{ build_number }}

Of note, though: build number, _should_ be inherited, while noarch is
_not_, so may not be necessary.

Really the best thing to do use code search to look through existing
feedstocks, and crib from those.

**Comment by jayqi** [comment]
Thanks for your help, and for the reminder about code search. (I had even just enabled the new fancy version yesterday!) My particular search only turned up a handful of cases, but it did prove that anchors/aliases can work. (I think the ones that turned up were in fact created by you.)

Documenting what seems to make the difference: it appears that aliases used in the output section can only reference anchors that are also defined in the output section. I got it working by defining the anchor on my first subpackage.

**Pull request merged**
